services:
  postgres:
    image: postgres:17
    container_name: swiftpay-postgres
    environment:
      POSTGRES_DB: swiftpay
      POSTGRES_USER: swiftpay
      POSTGRES_PASSWORD: swiftpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swiftpay -d swiftpay"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: swiftpay-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.0.1
    container_name: swiftpay-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  ledger-service:
    build:
      context: ./ledger-service
    container_name: swiftpay-ledger
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swiftpay
      SPRING_DATASOURCE_USERNAME: swiftpay
      SPRING_DATASOURCE_PASSWORD: swiftpay
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  transaction-gateway:
    build:
      context: ./transaction-gateway
    container_name: swiftpay-gateway
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swiftpay
      SPRING_DATASOURCE_USERNAME: swiftpay
      SPRING_DATASOURCE_PASSWORD: swiftpay
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LEDGER_SERVICE_URL: http://ledger-service:8081
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ledger-service:
        condition: service_started

volumes:
  postgres_data:
