apiVersion: v1
kind: Service
metadata:
  name: transaction-gateway
spec:
  selector:
    app: transaction-gateway
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-gateway
  template:
    metadata:
      labels:
        app: transaction-gateway
    spec:
      containers:
        - name: transaction-gateway
          image: swiftpay-transaction-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/swiftpay
            - name: SPRING_DATASOURCE_USERNAME
              value: swiftpay
            - name: SPRING_DATASOURCE_PASSWORD
              value: swiftpay
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: LEDGER_SERVICE_URL
              value: http://ledger-service:8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
